// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udqqplbxmhxhrkyzujol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkcXFwbGJ4bWh4aHJreXp1am9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MTgxNTUsImV4cCI6MjA1NjE5NDE1NX0.PuucsVfIxXSbxo_J1lj3GSUyt4u8jMiZnFaeofZ-ALU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);